# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosExample
  pod 'SwiftProtobuf', '~> 1.0'
  pod "imKeyBleLib", path: "../../blelibrary/imkey-ble-ios"
  pod 'LTHRadioButton'
#  pod 'CryptoSwift', '~> 1.3'


  target 'iosExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iosExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
