use_frameworks!

target 'imKeyBleLib_Example' do
  pod 'imKeyBleLib', :path => '../'

  target 'imKeyBleLib_Tests' do
    inherit! :search_paths

    
  end
end

pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  def installer.verify_no_static_framework_transitive_dependencies; end
end
